//! Entropy-source contract for the real OpenMLS laboratory.
//!
//! A local fake QRNG Open API server stands in for Entropy Core so that the
//! offline gates can prove (a) OpenMLS randomness and laboratory identity keys
//! are drawn from the configured QRNG source and (b) unavailability fails closed
//! without partial membership changes. Live Entropy Core is exercised only by the
//! ignored test at the end, and only when an endpoint is explicitly supplied.

mod common;

use agent_trust::entropy::EntropyConfig;
use agent_trust::mls::{EntropySource, MlsLab};
use common::FakeQrng;

fn ed25519_public(seed: &[u8]) -> Option<Vec<u8>> {
    let seed: [u8; 32] = seed.try_into().ok()?;
    Some(
        ed25519_dalek::SigningKey::from_bytes(&seed)
            .verifying_key()
            .to_bytes()
            .to_vec(),
    )
}

#[test]
fn qrng_source_supplies_openmls_randomness_for_group_operations() {
    // Catches a laboratory that accepts a QRNG source but keeps drawing OpenMLS
    // randomness from the local generator.
    let qrng = FakeQrng::start();
    let mut lab =
        MlsLab::with_entropy(EntropySource::Qrng(qrng.client())).expect("QRNG-backed lab");
    let after_create = qrng.entropy_posts();
    assert!(after_create > 0, "group creation must draw QRNG entropy");

    lab.add_member("bob").expect("bob joins with QRNG entropy");
    let after_add = qrng.entropy_posts();
    assert!(after_add > after_create, "admission must draw QRNG entropy");

    lab.add_member("carol").expect("carol joins");
    lab.remove_member("bob").expect("bob is removed");
    assert!(
        qrng.entropy_posts() > after_add,
        "removal commit with UpdatePath must draw QRNG entropy"
    );

    let wire = lab
        .protect("alice", b"qrng epoch", b"aad")
        .expect("alice protects");
    let (payload, aad) = lab.decrypt("carol", &wire).expect("carol decrypts");
    assert_eq!(payload, b"qrng epoch");
    assert_eq!(aad, b"aad");
    lab.verify_member_admission("carol")
        .expect("staged admission binding still verifies under QRNG");
}

#[test]
fn qrng_source_seeds_member_signature_keys() {
    // Catches identity keys generated by SignatureKeyPair::new (OsRng) while the
    // laboratory claims a QRNG entropy source.
    let qrng = FakeQrng::start();
    let mut lab =
        MlsLab::with_entropy(EntropySource::Qrng(qrng.client())).expect("QRNG-backed lab");
    lab.add_member("bob").expect("bob joins");

    let derived: Vec<Vec<u8>> = qrng
        .served_blocks()
        .iter()
        .filter_map(|block| ed25519_public(block))
        .collect();
    for member in ["alice", "bob"] {
        let key = lab
            .member_signature_key(member)
            .expect("member has a signature key");
        assert!(
            derived.contains(&key),
            "{member}'s signature key must derive from a QRNG-served 32-byte seed"
        );
    }
}

#[test]
fn qrng_unavailable_fails_closed_without_partial_membership() {
    // Catches silent fallback to local randomness and admission that leaves a
    // half-applied membership change when entropy is unavailable; then checks
    // that authorized progress resumes once entropy returns.
    let qrng = FakeQrng::start();
    let mut lab =
        MlsLab::with_entropy(EntropySource::Qrng(qrng.client())).expect("QRNG-backed lab");
    let epoch = lab.epoch();

    qrng.set_unavailable(true);
    let error = lab
        .add_member("bob")
        .expect_err("admission must fail closed while QRNG is unavailable");
    assert!(
        error.contains("Qrng("),
        "the failure must come from the QRNG source, got: {error}"
    );
    assert_eq!(lab.members(), vec!["alice".to_owned()]);
    assert_eq!(
        lab.epoch(),
        epoch,
        "failed admission must not advance the epoch"
    );

    qrng.set_unavailable(false);
    lab.add_member("bob")
        .expect("admission proceeds once QRNG entropy is available again");
    assert_eq!(lab.members(), vec!["alice".to_owned(), "bob".to_owned()]);
    let wire = lab
        .protect("alice", b"resumed", b"")
        .expect("alice protects");
    assert_eq!(
        lab.decrypt("bob", &wire).expect("bob decrypts").0,
        b"resumed"
    );
}

#[test]
fn qrng_unavailable_inside_openmls_commit_leaves_group_unchanged() {
    // Characterization test (written after implementation): removal needs no
    // new signature key, so the outage reaches OpenMLS commit/UpdatePath
    // creation itself. The removal must fail without a half-applied epoch, and
    // the same removal must succeed and exclude the retained copy afterwards.
    let qrng = FakeQrng::start();
    let mut lab =
        MlsLab::with_entropy(EntropySource::Qrng(qrng.client())).expect("QRNG-backed lab");
    lab.add_member("bob").expect("bob joins");
    lab.add_member("carol").expect("carol joins");
    lab.snapshot_member("bob", "revoked-copy")
        .expect("snapshot");
    let epoch = lab.epoch();

    qrng.set_unavailable(true);
    let posts = qrng.entropy_posts();
    let error = lab
        .remove_member("bob")
        .expect_err("removal commit must fail closed while QRNG is unavailable");
    assert!(
        error.contains("InsufficientRandomness"),
        "the failure must come from OpenMLS randomness, got: {error}"
    );
    assert_eq!(qrng.entropy_posts(), posts, "no entropy was served");
    assert_eq!(
        lab.epoch(),
        epoch,
        "failed removal must not advance the epoch"
    );
    assert_eq!(
        lab.members(),
        vec!["alice".to_owned(), "bob".to_owned(), "carol".to_owned()]
    );

    qrng.set_unavailable(false);
    lab.remove_member("bob")
        .expect("removal proceeds once QRNG entropy is available again");
    assert!(lab.epoch() > epoch);
    let wire = lab
        .protect("alice", b"successor", b"")
        .expect("alice protects");
    assert_eq!(
        lab.decrypt("carol", &wire).expect("carol decrypts").0,
        b"successor"
    );
    assert!(lab.decrypt("revoked-copy", &wire).is_err());
}

#[test]
fn qrng_unavailable_blocks_group_creation() {
    // Catches a constructor that falls back to local randomness.
    let qrng = FakeQrng::start();
    let client = qrng.client();
    qrng.set_unavailable(true);

    assert!(
        MlsLab::with_entropy(EntropySource::Qrng(client)).is_err(),
        "group creation must fail closed while QRNG is unavailable"
    );
}

/// Live Entropy Core smoke test, configured exactly like the laboratory: set
/// `AGENT_TRUST_ENTROPY_CONFIG=<file.toml>` or `AGENT_TRUST_QRNG_BASE_URL=<url>`.
/// Run only against an endpoint you are authorized to use; do not record the
/// endpoint in evidence:
///
/// `AGENT_TRUST_ENTROPY_CONFIG=entropy.toml cargo test --test mls_entropy -- --ignored`
#[test]
#[ignore = "requires a reachable QRNG Open API endpoint selected by entropy configuration"]
fn live_qrng_removal_excludes_retained_reader() {
    let config = EntropyConfig::from_env().expect("valid entropy configuration");
    assert_eq!(
        config.label(),
        "qrng",
        "configure a QRNG source for the live test"
    );
    let EntropySource::Qrng(client) = config.connect().expect("connect to live QRNG") else {
        unreachable!("a QRNG configuration yields a QRNG source");
    };
    let mut lab = MlsLab::with_entropy(EntropySource::Qrng(client.clone())).expect("live lab");
    lab.add_member("bob").expect("bob joins");
    lab.add_member("carol").expect("carol joins");
    lab.snapshot_member("bob", "revoked-copy")
        .expect("snapshot");
    lab.remove_member("bob").expect("bob removed");

    let wire = lab
        .protect("alice", b"live successor", b"")
        .expect("alice protects");
    assert_eq!(
        lab.decrypt("carol", &wire).expect("carol decrypts").0,
        b"live successor"
    );
    assert!(lab.decrypt("revoked-copy", &wire).is_err());
    let metrics = client.metrics_snapshot();
    assert!(metrics.entropy_requests_total > 0);
    assert_eq!(metrics.entropy_failures_total, 0);
    println!(
        "live QRNG: {} entropy requests, {} bytes",
        metrics.entropy_requests_total, metrics.entropy_bytes_total
    );
}
